name: 'Tate Carson '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#9bc2de'
    - '#0084cb'
    - '#015324'
    - '#99968a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
